// config/aws.ts
// AWS Configuration for the Image Upload App
// Auto-generated by setup script

export const AWS_CONFIG = {
  // Cognito Identity Pool ID
  IDENTITY_POOL_ID: process.env.EXPO_PUBLIC_IDENTITY_POOL_ID ?? '',
  
  // AWS Region
  REGION: process.env.EXPO_PUBLIC_REGION ?? 'eu-west-2',
  
  // Lambda Function Name
  LAMBDA_FUNCTION_NAME: process.env.EXPO_PUBLIC_LAMBDA_FUNCTION_NAME ?? '',
  
  // S3 Bucket Name
  BUCKET_NAME: process.env.EXPO_PUBLIC_BUCKET_NAME ?? ''
};
